### ISSUE TITLE
Any way to add the full game files?

### ISSUE THREAD

**Issue by JayTheMann** [Triang3l/WebQuake#28]
First of all, just wanted to say you guys have done a fabulous job so far. I've been running this on a chromebook, very stable, running at 100% speed. This is actually my first time playing it, and I would like to continue playing it on chrome. How's the full game feature coming? I would be willing to donate if you could assure me it would be coming in some reasonable amount of time.

**Comment by JayTheMann** [comment]
Whoops! This is the wrong github isn't it! Sorry.

**Comment by SpiritQuaddicted** [comment]
Not sure what the wrong repo might be. You can play full Quake and many mods by simply installing them to your own WebQuake instance.

**Comment by JayTheMann** [comment]
On chromebook?

**Comment by SpiritQuaddicted** [comment]
No idea what that is but WebQuake is just plain files you put on/in your webserver. You can add the game files, maps and mods there.

**Comment by JustH3LL** [comment]
Yeah, like just add the pak1.pak into the id1 folder and that's all you need
