### ISSUE TITLE
cant run mod files

### ISSUE THREAD

**Issue by Axisar** [Triang3l/WebQuake#29]
Hi there. i cant run mods. got the error everytime "Corrupted data file."
Even when i try to add not existing dir error is the same.
examles:
http://domain.tld/webquakedirwithindex.htm/?-game qr - dir exists, all files renamed to lowercase
http://domain.tld/webquakedirwithindex.htm/?-game airquake - dir exists, all files renamed to lowercase
http://domain.tld/webquakedirwithindex.htm/?-game notexist - dir not exists

console log output:
Host.Init
COM.js:301 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
COM.LoadPackFile @ COM.js:301
Sys.js:25 FindFile: qr/gfx/pop.lmp

Sys.js:44 Added packfile id1/pak0.pak (339 files)
Sys.js:44 Added packfile id1/pak1.pak (85 files)
Sys.js:44 Added packfile qr/pak0.pak (131 files)
Sys.js:44 Added packfile qr/pak1.pak (23 files)
Sys.js:44 Added packfile qr/pak2.pak (5 files)
Sys.js:44 Added packfile qr/pak3.pak (74 files)
Sys.js:47 Uncaught Error: Corrupted data file.
    at Object.Sys.Error (Sys.js:47)
    at Object.COM.CheckRegistered (COM.js:124)
    at Object.COM.Init (COM.js:172)
    at Object.Host.Init (Host.js:292)
    at window.onload (Sys.js:144)

**Comment by Triang3l** [comment]
Is pop.lmp modified in the .pak? Does the mod run fine on DOS Quake, WinQuake or GLQuake?

**Comment by Axisar** [comment]
well, seems something wrong with mods i tested. just downloaded quake rally from mod db, unzip, lowercase files. and its started.
