### ISSUE TITLE
W.LoadWadFile: couldn't load gfx.wad

### ISSUE THREAD

**Issue by Jimbow500** [Triang3l/WebQuake#35]
I don't know what I'm doing wrong, but I keep getting the error when I load the page.

**Comment by SpiritQuaddicted** [comment]
Which site?

What did you do?

What does the browser network log say?

**Comment by Jimbow500** [comment]
I took the pak files from steam and they were capitalized, I made them lowercase and that fixed it

**Comment by notqdoctor** [comment]
Does anyone know how to fix this?
