### ISSUE TITLE
Jumping is broken, you are kept on the same direction even when turning in flight

### ISSUE THREAD

**Issue by SpiritQuaddicted** [Triang3l/WebQuake#4]
In Quake you can turn in mid-air. Here this is not possible. If I jump and hold a turning key (or turn the mouse view), I will still fly into the "first" direction. This is a bug. In Quake I would have turned the jump's direction in the direction of the turn.

**Comment by LiamKarlMitchell** [comment]
Would this help to detect multiple keys pressed at once?

Store the events in an array by key and sample it frequently.

https://stackoverflow.com/questions/5203407/how-to-detect-if-multiple-keys-are-pressed-at-once-using-javascript
