### ISSUE TITLE
No official online demo

### ISSUE THREAD

**Issue by lambits** [Triang3l/WebQuake#40]
The online demo is broken since I only get the following error: 502 Bad Gateway. I managed to port it using 000webhost free version: http://webquake.000webhostapp.com/

**Comment by efess** [comment]
There's an unofficial "demo" based on a fork where some development has continued:

http://www.netquake.io

**Comment by Triang3l** [comment]
It's http://triang3l.github.io/WebQuake/, might be a temporary issue with github.io.
