### ISSUE TITLE
Where is "id1" folder?

### ISSUE THREAD

**Issue by e-oz** [Triang3l/WebQuake#5]
`Copy "id1" folder from the Quake folder to the folder where you put WebQuake.htm.` - I can't find this folder in repository.
Without this folder I'm getting http://198.211.127.71/quake/WebQuake.htm "Corrupted data file"

**Comment by jangrewe** [comment]
@jamm Simple, as always: Because you can.

**Comment by JustH3LL** [comment]
WebQuake is a source port, so it doesn't come with any Quake assets, it's just the engine. Same way Darkplaces or Quakespasm is, for example. anyways, the id1 folder should be on the same level as `index.htm`

so it would be something like this

    /id1/
    /WebQuake/
    index.htm
