### ISSUE TITLE
Using node.js as a server?

### ISSUE THREAD

**Issue by noway** [Triang3l/WebQuake#7]
Hi! I found your work pretty impressive!
For web server you use `abyss web server`, but why not simply use node.js, like in `Server/` part?
It would be much more uniform.

I think you should make `Client/` as private npm module, like `Server/` in my last Pull Request

**Comment by LiamKarlMitchell** [comment]
If you want to host web client via express, you could just put a JS file a level up, install express via.

```npm install -s express```

And run code like this to serve the files.

```
const express = require('express')
const app = express()
const port = 3000
const path = require('path')

app.get('/', function(req, res){
   res.sendFile(path.resolve('Client/index.htm'))
});

app.use(express.static('Client'));

app.listen(port, () => console.log(`Quake WebClient http server listening on port ${port}!`))
```
